// generated by calibZDC.cc (tag 20261001_Dzero_260426-yrefmva_PbPbUPC_HIForwardMerge_Dpt-2_wLumi_json, non-leveled events); do not edit by hand
// knot input position = c0 + c1*u + c2*u^2 with u = instLumi / kLumiUnit; reference = same pol2 at u = kURef (lumibin 0)
#pragma once
namespace zdccorr {
  const double kLumiUnit = 1e-06;
  const int kNKnots = 6;
  const double kULow = 0.213453, kUHigh = 6.35324; // instLumi is clamped to this range (in units of kLumiUnit)
  const double kURef = 0.213453;
  // [side: 0=Plus 1=Minus][knot: n90 n95 m1-s1 m1 m1+s1 m2][c0 c1 c2]
  const double kKnotPoly[2][6][3] = {
    {
      { 16.02679326, 8.099811148, -0.08639493561 },  // n90
      { 28.76746495, 10.48465036, -0.05840507834 },  // n95
      { 1694.901294, 69.63838399, 2.323715075 },  // m1lo
      { 2279.925071, 75.18699367, 3.129583098 },  // m1
      { 2867.02199, 79.11680829, 4.164812711 },  // m1hi
      { 4695.665795, 105.1673756, 12.46645182 }  // m2
    },
    {
      { 10.31252406, 6.335426698, 0.1227557941 },  // n90
      { 25.39182005, 6.814292498, 0.2766064959 },  // n95
      { 1453.478017, 123.8255222, 4.150272476 },  // m1lo
      { 2074.472807, 114.3618508, 8.301443444 },  // m1
      { 2698.766937, 102.1666998, 12.80481034 },  // m1hi
      { 4439.471011, 151.7002237, 22.35071776 }  // m2
    }
  };
};
