#pragma once
#include <algorithm>
#include <array>
#include <cmath>

#include "zdcLumiCorrParams.h" // generated by calibZDC.cc

// Lumi-dependent ZDC sum recalibration. ZDC' = f_L(ZDC), a continuous, strictly increasing map per side.
// Knots (input position at instLumi L -> fixed reference position, i.e. the lowest-lumi bin):
//   0 -> 0,  n90(L) -> n90_ref,  n95(L) -> n95_ref,  m1-s1 -> ref,  m1 -> ref,  m1+s1 -> ref,  m2 -> ref
// so that the noise core, the 1n peak (mean AND width) and the 2n position are the same at every lumi.
// Between the knots f is a monotone cubic Hermite spline (PCHIP, Fritsch-Carlson): C1, so the slope is continuous at the
// knots and the corrected spectrum (raw density / f') has no steps there. smooth = false gives the legacy piecewise-linear map.
// Above the last knot f continues with slope 1 (pure shift); below 0 it extrapolates with the slope at 0.
namespace zdccorr {
  enum Side { kPlus = 0, kMinus = 1 };

  inline double poly(const double* c, double u) { return c[0] + u * (c[1] + u * c[2]); }

  // side: kPlus / kMinus, lumi in the same units as params::lumibins. If dfdx != nullptr it receives f'(x).
  inline double correct(double x, double lumi, int side, bool smooth = true, double* dfdx = nullptr) {
    const double u = std::min(std::max(lumi / kLumiUnit, kULow), kUHigh);
    std::array<double, kNKnots + 1> xin, xout;
    xin[0] = 0.; xout[0] = 0.;
    int n = 1;
    for (int k = 0; k < kNKnots; k++) {
      const double in = poly(kKnotPoly[side][k], u), out = poly(kKnotPoly[side][k], kURef);
      if (in <= xin[n - 1] + 1.e-6 || out <= xout[n - 1] + 1.e-6) continue; // keep the map strictly increasing
      xin[n] = in; xout[n] = out; n++;
    }
    if (n < 2) { if (dfdx) *dfdx = 1.; return x; }

    // secants d[j] and widths h[j] of segment j = [j, j+1]
    std::array<double, kNKnots> h, d;
    for (int j = 0; j < n - 1; j++) { h[j] = xin[j + 1] - xin[j]; d[j] = (xout[j + 1] - xout[j]) / h[j]; }

    // knot slopes m[i]
    std::array<double, kNKnots + 1> m;
    if (!smooth || n == 2) {
      for (int i = 0; i < n; i++) m[i] = 0.; // unused by the linear path
    } else {
      for (int i = 1; i < n - 1; i++) { // weighted harmonic mean of the adjacent secants (monotone, no overshoot)
        const double w1 = 2. * h[i] + h[i - 1], w2 = h[i] + 2. * h[i - 1];
        m[i] = (w1 + w2) / (w1 / d[i - 1] + w2 / d[i]);
      }
      // slope at 0: one-sided three-point estimate, limited to [0, 3 d0]
      double m0 = ((2. * h[0] + h[1]) * d[0] - h[0] * d[1]) / (h[0] + h[1]);
      m[0] = std::min(std::max(m0, 0.), 3. * d[0]);
      // last knot: slope 1 so the join to the shifted tail is C1 (limited for monotonicity)
      m[n - 1] = std::min(1., 3. * d[n - 2]);
    }

    if (x >= xin[n - 1]) { if (dfdx) *dfdx = 1.; return xout[n - 1] + (x - xin[n - 1]); }
    if (x <= 0.) { // below zero: extrapolate with the first slope
      const double s = smooth && n > 2 ? m[0] : d[0];
      if (dfdx) *dfdx = s;
      return s * x;
    }
    int j = 0;
    while (j < n - 2 && x > xin[j + 1]) j++; // x in segment [j, j+1]
    if (!smooth || n == 2) {
      if (dfdx) *dfdx = d[j];
      return xout[j] + (x - xin[j]) * d[j];
    }
    const double t = (x - xin[j]) / h[j], t2 = t * t, t3 = t2 * t;
    const double h00 = 2. * t3 - 3. * t2 + 1., h10 = t3 - 2. * t2 + t, h01 = -2. * t3 + 3. * t2, h11 = t3 - t2;
    if (dfdx) {
      const double dh00 = 6. * t2 - 6. * t, dh10 = 3. * t2 - 4. * t + 1., dh01 = -6. * t2 + 6. * t, dh11 = 3. * t2 - 2. * t;
      *dfdx = (dh00 * xout[j] + dh01 * xout[j + 1]) / h[j] + dh10 * m[j] + dh11 * m[j + 1];
    }
    return h00 * xout[j] + h10 * h[j] * m[j] + h01 * xout[j + 1] + h11 * h[j] * m[j + 1];
  }
}
