#pragma once
#include <algorithm>
#include <array>
#include <cmath>

#include "hfLumiCorrParams.h" // generated by calibHF.cc

// Lumi-dependent recalibration of the 0n-side HFEMax: HF' = f_L(HF), a continuous, strictly increasing quantile-transfer map per side.
// Knots (input position at instLumi L -> fixed reference position, i.e. the lowest-lumi bin):
//   0 -> 0,  x_p(L) -> x_p(L_ref) for the quantile levels p in kLevels,  kHFEnd -> kHFEnd
// so that the 0n-side spectrum has the same CDF at every lumi below the last quantile knot; from kHFEnd on f is the identity.
// Between the knots f is a monotone cubic Hermite spline (PCHIP, Fritsch-Carlson), as in zdcLumiCorrection.h.
// Only meant for the 0n side (Plus when ZDCsumPlus < 1500, Minus when ZDCsumMinus < 1500).
namespace hfcorr {
  enum Side { kPlus = 0, kMinus = 1 };

  inline double poly(const double* c, double u) { return c[0] + u * (c[1] + u * c[2]); }

  // side: kPlus / kMinus, lumi in the same units as params::lumibins. If dfdx != nullptr it receives f'(x).
  inline double correct(double x, double lumi, int side, double* dfdx = nullptr) {
    if (x >= kHFEnd) { if (dfdx) *dfdx = 1.; return x; }
    const double u = std::min(std::max(lumi / kLumiUnit, kULow[side]), kUHigh[side]);
    constexpr int NMAX = kNKnots + 2;
    std::array<double, NMAX> xin, xout;
    xin[0] = 0.; xout[0] = 0.;
    int n = 1;
    for (int k = 0; k < kNKnots; k++) {
      const double in = poly(kKnotPoly[side][k], u), out = poly(kKnotPoly[side][k], kURef[side]);
      if (in <= xin[n - 1] + 1.e-6 || out <= xout[n - 1] + 1.e-6 || in >= kHFEnd - 1.e-6 || out >= kHFEnd - 1.e-6) continue; // strictly increasing
      xin[n] = in; xout[n] = out; n++;
    }
    xin[n] = kHFEnd; xout[n] = kHFEnd; n++;

    std::array<double, NMAX> h, d, m;
    for (int j = 0; j < n - 1; j++) { h[j] = xin[j + 1] - xin[j]; d[j] = (xout[j + 1] - xout[j]) / h[j]; }
    for (int i = 1; i < n - 1; i++) { // weighted harmonic mean of the adjacent secants (monotone, no overshoot)
      const double w1 = 2. * h[i] + h[i - 1], w2 = h[i] + 2. * h[i - 1];
      m[i] = (w1 + w2) / (w1 / d[i - 1] + w2 / d[i]);
    }
    const double m0 = ((2. * h[0] + h[1]) * d[0] - h[0] * d[1]) / (h[0] + h[1]); // one-sided three-point slope at 0, limited to [0, 3 d0]
    m[0] = std::min(std::max(m0, 0.), 3. * d[0]);
    m[n - 1] = std::min(1., 3. * d[n - 2]); // identity slope at kHFEnd (C1 join), limited for monotonicity

    if (x <= 0.) { if (dfdx) *dfdx = m[0]; return m[0] * x; }
    int j = 0;
    while (j < n - 2 && x > xin[j + 1]) j++; // x in segment [j, j+1]
    const double t = (x - xin[j]) / h[j], t2 = t * t, t3 = t2 * t;
    const double h00 = 2. * t3 - 3. * t2 + 1., h10 = t3 - 2. * t2 + t, h01 = -2. * t3 + 3. * t2, h11 = t3 - t2;
    if (dfdx) {
      const double dh00 = 6. * t2 - 6. * t, dh10 = 3. * t2 - 4. * t + 1., dh01 = -6. * t2 + 6. * t, dh11 = 3. * t2 - 2. * t;
      *dfdx = (dh00 * xout[j] + dh01 * xout[j + 1]) / h[j] + dh10 * m[j] + dh11 * m[j + 1];
    }
    return h00 * xout[j] + h10 * h[j] * m[j] + h01 * xout[j + 1] + h11 * h[j] * m[j + 1];
  }
}
